<?php

namespace Modules\MaterialGrabber\Repositories;

use Doctrine\ORM\QueryBuilder;
use Modules\MaterialGrabber\Entities\Bibelstelle;
use StevenBuehner\BibleVerseBundle\Entity\BibleVerse;
use StevenBuehner\BibleVerseBundle\Interfaces\BibleVerseInterface;

/**
 * BibelstelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BibelstelleRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * @param $bookId
	 * @return int[]
	 */
	public function getAllExistingChaptersOfABook($bookId) {
		// From Chapter
		$query1 = $this->getEntityManager()->createQuery(
			'SELECT DISTINCT B.fromChapter as chapter FROM ' . $this->_entityName . ' B WHERE B.bookId=:bookId'
		);
		$query2 = $this->getEntityManager()->createQuery(
			'SELECT DISTINCT B.toChapter as chapter FROM ' . $this->_entityName . ' B WHERE B.bookId=:bookId'
		);

		$query1->setParameter('bookId', $bookId);
		$query2->setParameter('bookId', $bookId);

		$result = [];
		foreach ($query1->getArrayResult() as $data) {
			$result[(int) $data['chapter']] = TRUE;
		}
		foreach ($query2->getArrayResult() as $data) {
			$result[(int) $data['chapter']] = TRUE;
		}

		$result = array_keys($result);
		usort($result, function ($a, $b) {
			return $a - $b;
		});

		return $result;
	}

	/**
	 * @param int[] $grabberIds
	 */
	public function getExistingBooksByGrabberIds($grabberIds) {
		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('B')
				   ->select('B.bookId')
				   ->join('B.material', 'M')
				   ->join('M.link', 'L')
				   ->where('L.grabber IN (:grabberids)')
				   ->groupBy('B.bookId')
				   ->orderBy('B.bookId', 'ASC')
				   ->setParameter('grabberids', array_values($grabberIds));

		$result = [];
		$query  = $qb->getQuery();

		foreach ($query->getArrayResult() as $data) {
			$result[] = $data['bookId'];
		}

		return $result;
	}

	/**
	 * @param int|int[] $bookId
	 * @param int[]     $grabberIds
	 * @param int       $page
	 * @param int       $anzStellen
	 * @return Bibelstelle[]
	 */
	public function getBibelStellenByGrabber($bookId, $grabberIds, $page = 1, $anzStellen = 50) {

		$offset     = max(($page - 1) * $anzStellen, 1);
		$grabberIds = is_array($grabberIds) ? $grabberIds : [$grabberIds];

		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('B')
				   ->select('B')
				   ->join('B.material', 'M')
				   ->join('M.link', 'L')
				   ->where('L.grabber IN (:grabberids)')
				   ->andWhere('B.bookId = :bookId')
				   ->orderBy('B.start', 'ASC')
				   ->addOrderBy('B.end', 'DESC')
				   ->setParameter('grabberids', array_values($grabberIds))
				   ->setParameter('bookId', $bookId)
				   ->setFirstResult($offset)
				   ->setMaxResults($anzStellen);

		$query = $qb->getQuery();

		return $query->getResult();
	}

	/**
	 * @param int[] $grabberIds
	 * @return int
	 */
	public function countBibelStellenByGrabber($grabberIds) {
		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('B')
				   ->select('count(DISTINCT B)')
				   ->join('B.material', 'M')
				   ->join('M.link', 'L')
				   ->where('L.grabber IN (:grabberids)')
				   ->setParameter('grabberids', array_values($grabberIds));

		$query = $qb->getQuery();

		return $query->getSingleScalarResult();

	}


	/**
	 * @return int[] bookIds
	 */
	public function getAllExistingBooks() {

		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('B')
				   ->select('B.bookId')
				   ->groupBy('B.bookId')
				   ->orderBy('B.bookId', 'ASC');

		$query = $qb->getQuery();

		$result = [];
		foreach ($query->getArrayResult() as $data) {
			$result[] = $data['bookId'];
		}

		return $result;
	}

	/**
	 * @param int $bookId
	 * @param int $page
	 * @param int $anzStellen
	 * @return Bibelstelle[]
	 */
	public function getBibelStellen($bookId, $page = 1, $anzStellen = 50) {

		return $this->findBy(
			$criteria = ['bookId' => (int) $bookId],
			$order = ['start' => 'ASC', 'end' => 'DESC'],
			$limit = $anzStellen,
			$offset = $page * $anzStellen
		);

	}

	/**
	 * @param BibleVerse $bv
	 * @return Bibelstelle
	 */
	public function getBibelstelle(BibleVerse $bv) {

		$result = $this->findOneBy(['bookId' => $bv->getBookId(),
									'start'  => $bv->getStart(),
									'end'    => $bv->getEnd()
								   ]);


		if (NULL === $result) {
			$result = new Bibelstelle();
			$result->setVerse(
				$bv->getBookId(),
				$bv->getFromChapter(),
				$bv->getFromVerse(),
				$bv->getToChapter(),
				$bv->getToVerse()
			);
			$this->getEntityManager()->persist($result);
			$this->getEntityManager()->flush($result);
		}

		return $result;
	}

	/**
	 * @param BibleVerseInterface $bv
	 * @param null|int            $grabberId
	 * @return BibleVerse[]
	 */
	public function findAllBibleVerses(BibleVerseInterface $bv, $grabberId = NULL) {


		$dql = 'DISTINCT SELECT ' . $this->getClassName() . ' b ';
		$dql .= 'WHERE b.bookId = :bookId';

		$dql .= '(`from`  >= :from  AND `to`  <= :to ) || ';
		$dql .= '(`from`  <= :from  AND `to`  >= :to ) || ';
		$dql .= '(`from`  <= :from  AND `to`  <= :to ) )';


		$query = $this->getEntityManager()->createQuery($dql);
		$query->setParameter('bookId', $bv->getBookId());
		$query->setParameter('fromVerse', $bv->getFromVerse());
		$query->setParameter('toVerse', $bv->getToVerse());
		$query->setParameter('fromChapter', $bv->getFromChapter());
		$query->setParameter('toChapter', $bv->getToChapter());


	}


}
