<?php

namespace Modules\MaterialGrabber\Repositories;

use Doctrine\ORM\EntityRepository;
use Modules\MaterialGrabber\Entities\GrabberConf;

/**
 * GrabberBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrabberConfRepository extends EntityRepository {

	/**
	 * @param string $name
	 * @return null|GrabberConf
	 */
	public function getGrabberByName($name) {
		return $this->findOneBy(['name' => $name]);
	}
}
