<?php

namespace Modules\MaterialGrabber\Repositories;

use Doctrine\ORM\EntityRepository;
use Modules\MaterialGrabber\Entities\Link;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository {

	public function findNextLinkToRun() {
		return $this->findOneBy(['status' => Link::$STATUS_WAITING], $order = ['id' => 'ASC']);
	}

	/**
	 * @param Link $link
	 * @return Link[]
	 */
	public function getMd5Dubletten(Link $link) {
		$queryBuilder = $this->createQueryBuilder('l');
		// $queryBuilder->where($queryBuilder->expr()->notIn('l.id', $link->getId()));
		$queryBuilder->where('id != :id AND md5Cache == :md5Cache')->setParameter('id', $link->getId())
					 ->setParameter('md5Cache', $link->getMd5Cache());

		return $query = $queryBuilder->getQuery()->getResult();
	}

	public function countByGrabberIDs($grabberIds) {
		$grabberIds = is_array($grabberIds) ? $grabberIds : [$grabberIds];

		$qb = $this->createQueryBuilder('l')
				   ->select('Count(l)')
				   ->where('l.grabber IN (:grabberIds)')
				   ->setParameter('grabberIds', array_values($grabberIds));

		$query = $qb->getQuery();

		return (int) $query->getSingleScalarResult();
	}

	public function countByGrabberIDsAndStatus($grabberIDs, $status) {
		$grabberIDs = is_array($grabberIDs) ? $grabberIDs : [$grabberIDs];
		$status     = is_array($status) ? $status : [$status];

		$qb = $this->createQueryBuilder('l')
				   ->select('Count(l)')
				   ->where('l.grabber IN (:grabberIds)')
				   ->andWhere('l.status in (:status)')
				   ->setParameter('grabberIds', array_values($grabberIDs))
				   ->setParameter('status', array_values($status));

		$query = $qb->getQuery();

		return (int) $query->getSingleScalarResult();
	}


}
