<?php

namespace Modules\MaterialGrabber\Repositories;

use Doctrine\ORM\EntityRepository;
use Modules\MaterialGrabber\Entities\Bibelstelle;
use Modules\MaterialGrabber\Entities\Link;
use Modules\MaterialGrabber\Entities\Material;
use Modules\MaterialGrabber\Entities\Stichwort;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends EntityRepository {

	public function removeMaterialAndAssociations(Link $link, $cleanupStichwoerter = TRUE, $cleanupBibelstellen = TRUE) {

		/** @var Material[] $result */
		$result = $this->findBy($criteria = ['link' => $link]);

		/**
		 * @var Material[] $result
		 */
		foreach ($result as $material) {
			$bst   = $material->getBibelstelle()->toArray();
			$stich = $material->getStichwort()->toArray();

			$material->clearBibelstellen();
			$material->clearStichworte();
			$material->setLink(NULL);
			$this->getEntityManager()->remove($material);


			if ($cleanupBibelstellen) {
				foreach ($bst as $bs) {
					/** @var $bs Bibelstelle */
					if (count($bs->getMaterial()) == 0) {
						$this->getEntityManager()->remove($bs);
					}
				}
			}

			if ($cleanupStichwoerter) {
				foreach ($stich as $st) {
					/** @var $st Stichwort */
					if (count($st->getMaterial()) == 0) {
						$this->getEntityManager()->remove($st);
					}
				}
			}

			$this->getEntityManager()->flush($material);
		}
	}

}
