<?php

namespace Modules\MaterialGrabber\Repositories;

use Doctrine\ORM\QueryBuilder;
use Modules\MaterialGrabber\Entities\Stichwort;

/**
 * StichwortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StichwortRepository extends \Doctrine\ORM\EntityRepository {

	public function getStichwortFromText($stichwortText) {

		$result = $this->findOneBy(['text' => $stichwortText]);

		if (NULL === $result) {
			$result = new Stichwort();
			$result->setText($stichwortText);
			$this->getEntityManager()->persist($result);
			$this->getEntityManager()->flush($result);
		}

		return $result;
	}

	/**
	 * @param int[] $grabberIds
	 * @param int   $page
	 * @param int   $anzStellen
	 * @return Stichwort[]
	 */
	public function getStichworteByGrabber($grabberIds, $page = 1, $anzStellen = 50) {

		$offset     = max(($page - 1) * $anzStellen, 1);
		$grabberIds = is_array($grabberIds) ? $grabberIds : [$grabberIds];

		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('S')
				   ->select('S')
				   ->join('S.material', 'M')
				   ->join('M.link', 'L')
				   ->where('L.grabber IN (:grabberids)')
				   ->orderBy('S.text', 'ASC')
				   ->setParameter('grabberids', array_values($grabberIds))
				   ->setFirstResult($offset)
				   ->setMaxResults($anzStellen);

		$query = $qb->getQuery();

		return $query->getResult();
	}

	/**
	 * @param int[] $grabberIds
	 * @return int
	 */
	public function countStichworteByGrabber($grabberIds) {
		/** @var QueryBuilder $qb */
		$qb = $this->createQueryBuilder('S')
				   ->select('count(DISTINCT S)')
				   ->join('S.material', 'M')
				   ->join('M.link', 'L')
				   ->where('L.grabber IN (:grabberids)')
				   ->setParameter('grabberids', array_values($grabberIds));

		$query = $qb->getQuery();

		return $query->getSingleScalarResult();

	}
}
