<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\DB;

/**
 * Class Material
 *
 * @package App\Models
 * @property int $id
 * @property string $title
 * @property string $description
 * @property int $rating (0-20)
 * @property boolean $from_bot
 * @property int $created_by
 * @property int $modified_by
 * @property int $author_id
 * @property int $flag;
 * @property int|null $icon_of_bundle
 * @property Keyword $author
 * @property Collection $resources;
 * @property Collection $keywords;
 * @property Collection $foreignIds;
 * @property Collection $persons;
 * @property Collection $languages;
 * @property Collection $tags;
 * @property Collection $places;
 * @property User|NULL $creator;
 * @property User|NULL $modifier;
 * @property Collection $bibleverses;
 * @property            $updated_at;
 * @property            $created_at;
 */
class Material extends Model {
	use HasFactory;

	const MAX_RATING = 20;

	protected $casts = [
		'from_bot'       => 'boolean',
		'description'    => 'string',
		'flag'           => 'integer',
		'icon_of_bundle' => 'integer',
	];

	protected $attributes = [
		'rating'      => NULL,
		'description' => '',
		'from_bot'    => FALSE
	];

	protected $fillable = [
		'title', 'description', 'rating', 'from_bot', 'flag', 'icon_of_bundle', 'created_at'
	];

	protected $guarded = [
		'id', 'created_by', 'modified_by', 'updated_at'
	];

	protected $hidden = [
		'author_id'
	];

	public function __construct(array $attributes = []) {
		parent::__construct($attributes);
	}

	/**
	 *
	 * Works but missing pivot in relation (!)
	 *
	 * @param $userId
	 * @return mixed
	 */
	public function foreignResources($userId) {

		$fi = new        ForeignResourceId();

		$query = DB::table($fi->getTable())
			->where('user_id', $userId)
			->join('resources', $fi->getTable() . '.resource_id', 'resources.id')
			->join('material_resource', 'resources.id', 'material_resource.resource_id')
			->where('material_resource.material_id', $this->id)
			->select($fi->getTable() . '.*');

		$builder = $fi->newEloquentBuilder($query); //->with('resource');
		$builder->setModel($fi);
		$builder->with('resource');

		$c = $builder->get();

		return $c;
	}

	public function persons() {
		return $this->keyWordClassAndChildren('person');
	}

	/**
	 * @param $class
	 * @return BelongsToMany
	 */
	protected function keyWordClassAndChildren($type) {
		return $this->belongsToMany(Keyword::class, 'keyword_material', 'material_id', 'keyword_id')
			->where('type', '=', $type)
			->withPivot('relevance')
			->using(MaterialKeyword::class);
	}

	public function languages() {
		return $this->keyWordClassAndChildren('lang');
	}

	public function tags() {
		return $this->keyWordClassAndChildren('key');
	}

	public function places() {
		return $this->keyWordClassAndChildren('place');
	}

	public function creator() {
		return $this->belongsTo(User::class, 'created_by');
	}

	public function modifier() {
		return $this->belongsTo(User::class, 'modified_by');
	}

	public function author() {
		return $this->belongsTo(Keyword::class, 'author_id');
	}

	public function setRatingAttribute($value) {
		// Not more than 20!
		$this->attributes['rating'] = min($value, 20);
	}

	public function delete() {
		$this->resources()->detach();
		$this->keywords()->detach();
		$this->bibleverses()->detach();

		$this->foreignIds()->delete();

		return parent::delete(); // TODO: Change the autogenerated stub
	}

	public function resources() {
		return $this->belongsToMany(Resource::class, 'material_resource', 'material_id', 'resource_id')
			->withPivot('limitation')
			->using(MaterialResource::class);
	}

	public function keywords() {
		return $this->belongsToMany(Keyword::class, 'keyword_material', 'material_id', 'keyword_id')
			->withPivot('relevance')
			->using(MaterialKeyword::class);
	}

	/**
	 * @return BelongsToMany
	 */
	public function bibleverses() {
		return $this->belongsToMany(Bibleverse::class)
			->withPivot('relevance')
			->using(MaterialBibleverse::class);
	}

	public function foreignIds() {
		return $this->hasMany(ForeignMaterialId::class);
	}

	public function usages() {
		return $this->hasMany(MaterialUsage::class, 'material_id');
	}


}
