<?php

namespace App\Models;

use App\Jobs\UpdateResourceHashes;
use App\Services\PreviewGeneration\Generators\NoPreviewGenerator;
use App\Services\PreviewGeneration\Interfaces\PreviewGeneratorInterface;
use App\Services\TagExtraction\ResourceHandles\HandlerInterface;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Nanigans\SingleTableInheritance\SingleTableInheritanceTrait;

/**
 * Class Resource
 *
 * @package App
 * @property int        $id
 * @property int        $created_by
 * @property string     $remote_path
 * @property string     $local_path
 * @property string     $content_hash
 * @property string     $notes
 * @property bool       $is_public
 * @property            $created_at
 * @property            $updated_at
 * @property int        $user_id
 * @property User       $creator
 * @property Collection $materials
 */
class Resource extends Model {
	use SingleTableInheritanceTrait;

	static           $allResourceTypeKeys   = ['res', 'link', 'file', 'text', 'book', 'audio', 'video', 'image', 'doc'];
	protected static $singleTableTypeField  = 'type';
	protected static $singleTableSubclasses = [Url::class, File::class, Text::class, Book::class];
	protected static $singleTableType       = 'res';

	protected $additionalEditViews = [];
	protected $table               = 'resources';
	protected $casts               = [
		'is_public' => 'boolean',
		'options'   => 'array',
		// 'created_at' => 'Date'
	];
	protected $guarded             = [
		'id', 'created_by', 'options', 'content_hash', 'type', 'created_at', 'updated_at'
	];

	protected $fillable = [
		'remote_path', 'notes', 'is_public'
	];

	protected $hidden = ['options', 'local_path'];

	public function __construct(array $attributes = []) {
		$this->options   = [];
		$this->is_public = FALSE;
		$this->notes     = '';

		parent::__construct($attributes);
	}

	public static function getSingleTableClass($key) {
		$map = self::getSingleTableTypeMap();

		return isset($map[$key]) ? $map[$key] : NULL;
	}

	public static function getValidationRules() {
		return [
			'is_public'   => 'boolean|nullable',
			'remote_path' => 'nullable|url',
			'notes'       => 'nullable|string'
		];

		// Type, local_path, content_hash, options, file dürfen nicht berücksichtigt werden ... das sind keine Daten, die gesetzt werden sollen an dieser Stelle
		// 'type'=> 'in:' . join(',', array_keys(self::getSingleTableTypeMap())),
	}

	public function toArray() {
		$attributes = $this->attributesToArray();
		$attributes = array_merge($attributes, $this->relationsToArray());

		if (isset($attributes['pivot']['material_id'])) {
			// I need that stuff in vuejs
			// unset($attributes['pivot']['material_id']);
		}

		if (isset($attributes['pivot']['resource_id'])) {
			// I need that stuff in vuejs
			// unset($attributes['pivot']['resource_id']);
		}

		return $attributes;
	}

	/**
	 * @return HandlerInterface[]
	 */
	public function getTagExtractionClasses() {
		return [
		];
	}

	public function creator() {
		return $this->belongsTo(User::class, 'created_by');
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function foreignIds() {
		return $this->hasMany(ForeignResourceId::class, 'resource_id');
	}

	/**
	 * Returns an array of additional EditViews that will be loaded on edit (by ResourceController)
	 *
	 * @return array
	 */
	public function getAdditionalEditViews() {
		return $this->additionalEditViews;
	}

	/**
	 * @param $size
	 * @return PreviewGeneratorInterface
	 */
	public function getPreviewGenerator($size = 'large') {
		return resolve(NoPreviewGenerator::class);
	}

	public function delete() {
		$this->materials()->detach();

		return parent::delete(); // TODO: Change the autogenerated stub
	}

	/**
	 * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
	 */
	public function materials() {
		return $this->belongsToMany(Material::class, 'material_resource', 'resource_id', 'material_id')
					->withPivot('limitation')
					->using(MaterialResource::class);
	}

	/**
	 * @return array of jobs that need to be run after creating this resource
	 */
	public function getPostCreateJobs() {
		return [new UpdateResourceHashes($this)];
	}

	/**
	 * @param $key string
	 * @return bool
	 */
	protected function hasOption(string $key) {
		$options = $this->getAttribute('options');

		return isset($options[$key]);
	}

	/**
	 * @param $key string
	 * @param $value mixed
	 */
	protected function setOption(string $key, $value) {
		$options       = $this->getAttribute('options');
		$options[$key] = $value;
		$this->setAttribute('options', $options);
	}

	/**
	 * @param string $key
	 * @param mixed  $default
	 * @return mixed|null
	 */
	protected function getOption(string $key, $default = NULL) {
		$options = $this->getAttribute('options');

		if (isset($options[$key])) {
			return $options[$key];
		}

		return $default;
	}

	protected function getTypeAttribute() {
		return static::$singleTableType;
	}

	/**
	 * @param string $key
	 */
	protected function removeOption(string $key) {
		$options = $this->getAttribute('options');

		if (isset($options[$key])) {
			unset($options[$key]);
			$this->setAttribute('options', $options);
		}
	}

}
