<?php

namespace StevenBuehner\MaterialResourceStructureBundle\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * MaterialTypRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialTypeRepository extends NestedTreeRepository {

}
