<?php

namespace StevenBuehner\MaterialResourceStructureBundle\Repository;

use StevenBuehner\MaterialResourceStructureBundle\Entity\MaterialType;

/**
 * MaterialTypRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialTypRepository extends \Doctrine\ORM\EntityRepository {

}
