[program:materialpool-default]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /srv/materialpool/current/artisan queue:work database --queue=default,resource-previews-low --sleep=3 --tries=50 --timeout=120 --max-time=3600
directory=/srv/materialpool/current
user=www-data
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=150
redirect_stderr=true
stdout_logfile=/var/log/supervisor/materialpool-worker.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5

[program:materialpool-downloads]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /srv/materialpool/current/artisan queue:work material_downloads --queue=material-downloads --sleep=3 --tries=1 --timeout=3600 --max-time=7200
directory=/srv/materialpool/current
user=www-data
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=3700
redirect_stderr=true
stdout_logfile=/var/log/supervisor/materialpool-downloads.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
