<?php

namespace StevenBuehner\MaterialResourceStructureBundle\Repository;

/**
 * keywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
