<?php

namespace StevenBuehner\MaterialResourceStructureBundle\Repository;

/**
 * MaterialKeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialKeywordRepository extends \Doctrine\ORM\EntityRepository
{
}
